port: 8893
index_dbPath: /home/ps/Desktop/RAGLAB/data/retrieval/colbertv2.0_embedding/wiki2023
text_dbPath: /home/ps/Desktop/RAGLAB/data/retrieval/colbertv2.0_passages/wiki2023/enwiki-20230401.tsv
retriever_modelPath: ./model/colbertv2.0
